import type { Notification } from "./types";

// 12 sample notifications covering all notification types.
// These appear in the notification bell popover in the sidebar.

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "overdue_task",
    title: "Task overdue",
    message: "\"Send updated SOW by Friday\" is 2 days overdue",
    account_name: "Acme Corp",
    account_id: "1",
    read: false,
    created_at: "2026-02-16T09:00:00Z",
  },
  {
    id: "n2",
    type: "health_drop",
    title: "Health status dropped",
    message: "Globex Inc health changed from Healthy to At Risk",
    account_name: "Globex Inc",
    account_id: "2",
    read: false,
    created_at: "2026-02-15T14:20:00Z",
  },
  {
    id: "n3",
    type: "deal_stagnant",
    title: "Deal hasn't moved",
    message: "\"Umbrella Co — Initial Assessment\" has been in Lead stage for 15 days",
    account_name: "Umbrella Co",
    account_id: "4",
    read: false,
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "n4",
    type: "upcoming_renewal",
    title: "Renewal approaching",
    message: "Acme Corp annual renewal is due in 45 days",
    account_name: "Acme Corp",
    account_id: "1",
    read: false,
    created_at: "2026-02-14T08:00:00Z",
  },
  {
    id: "n5",
    type: "new_intelligence",
    title: "New intelligence",
    message: "3 new email insights extracted for Acme Corp",
    account_name: "Acme Corp",
    account_id: "1",
    read: true,
    created_at: "2026-02-13T16:30:00Z",
  },
  {
    id: "n6",
    type: "mention",
    title: "You were mentioned",
    message: "Sarah Chen mentioned you in a note on Globex Inc",
    account_name: "Globex Inc",
    account_id: "2",
    read: true,
    created_at: "2026-02-13T14:00:00Z",
  },
  {
    id: "n7",
    type: "workflow_complete",
    title: "Workflow completed",
    message: "\"Thrive Local Onboarding\" completed for Initech",
    account_name: "Initech",
    account_id: "3",
    read: true,
    created_at: "2026-02-12T17:00:00Z",
  },
  {
    id: "n8",
    type: "overdue_task",
    title: "Task overdue",
    message: "\"Prepare quarterly budget review deck\" is 1 day overdue",
    account_name: "Globex Inc",
    account_id: "2",
    read: true,
    created_at: "2026-02-12T09:00:00Z",
  },
  {
    id: "n9",
    type: "new_intelligence",
    title: "New intelligence",
    message: "Meeting transcript analyzed for Acme Corp weekly sync",
    account_name: "Acme Corp",
    account_id: "1",
    read: true,
    created_at: "2026-02-11T16:30:00Z",
  },
  {
    id: "n10",
    type: "deal_stagnant",
    title: "Deal hasn't moved",
    message: "\"Globex Q3 Strategy Package\" has been in Proposal for 10 days",
    account_name: "Globex Inc",
    account_id: "2",
    read: true,
    created_at: "2026-02-11T10:00:00Z",
  },
  {
    id: "n11",
    type: "upcoming_renewal",
    title: "Renewal approaching",
    message: "Globex Inc contract renewal is due in 60 days",
    account_name: "Globex Inc",
    account_id: "2",
    read: true,
    created_at: "2026-02-10T08:00:00Z",
  },
  {
    id: "n12",
    type: "health_drop",
    title: "Health status dropped",
    message: "Waystar Royco health changed from At Risk to Churning",
    account_name: "Waystar Royco",
    account_id: "5",
    read: true,
    created_at: "2026-02-09T14:00:00Z",
  },
];
