import type { ActivityLogEntry } from "./types";

// 25+ sample activity entries covering all event types.
// These feed into the Dashboard's Recent Activity section,
// the Activity Feed page, and the notification system.

export const mockActivityLog: ActivityLogEntry[] = [
  {
    id: "act-1",
    event_type: "deal_stage_changed",
    description: "Moved \"Acme Corp — Expanded Scope\" from Lead to Proposal",
    actor_name: "Mike Torres",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { deal_id: "d3", from_stage: "lead", to_stage: "proposal" },
    created_at: "2026-02-16T09:15:00Z",
  },
  {
    id: "act-2",
    event_type: "task_completed",
    description: "Completed \"Review resource allocation\"",
    actor_name: "Sarah Chen",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { task_id: "t4" },
    created_at: "2026-02-16T08:45:00Z",
  },
  {
    id: "act-3",
    event_type: "intelligence_received",
    description: "New email intelligence: Q2 renewal timeline discussed",
    actor_name: "System",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { intelligence_id: "1", source: "email" },
    created_at: "2026-02-15T16:30:00Z",
  },
  {
    id: "act-4",
    event_type: "health_changed",
    description: "Health status changed from Healthy to At Risk",
    actor_name: "System",
    account_name: "Globex Inc",
    account_id: "2",
    metadata: { from: "healthy", to: "at_risk" },
    created_at: "2026-02-15T14:20:00Z",
  },
  {
    id: "act-5",
    event_type: "email_synced",
    description: "3 new emails synced from Gmail",
    actor_name: "System",
    account_name: null,
    account_id: null,
    metadata: { count: 3 },
    created_at: "2026-02-15T10:30:00Z",
  },
  {
    id: "act-6",
    event_type: "note_added",
    description: "Added note: \"Client mentioned potential budget increase for Q3\"",
    actor_name: "Sarah Chen",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: {},
    created_at: "2026-02-14T17:00:00Z",
  },
  {
    id: "act-7",
    event_type: "workflow_applied",
    description: "Applied \"Thrive Local Onboarding\" workflow",
    actor_name: "Mike Torres",
    account_name: "Umbrella Co",
    account_id: "4",
    metadata: { workflow_id: "wf-thrive-onboarding" },
    created_at: "2026-02-14T15:30:00Z",
  },
  {
    id: "act-8",
    event_type: "task_created",
    description: "Created task \"Send updated SOW by Friday\"",
    actor_name: "System",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { task_id: "t1", source: "auto" },
    created_at: "2026-02-14T14:00:00Z",
  },
  {
    id: "act-9",
    event_type: "deal_created",
    description: "Created deal \"Umbrella Co — Initial Assessment\" ($15,000)",
    actor_name: "Mike Torres",
    account_name: "Umbrella Co",
    account_id: "4",
    metadata: { deal_id: "d1", amount: 15000 },
    created_at: "2026-02-14T11:00:00Z",
  },
  {
    id: "act-10",
    event_type: "meeting_logged",
    description: "Weekly sync meeting transcript processed",
    actor_name: "System",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { intelligence_id: "2" },
    created_at: "2026-02-13T16:00:00Z",
  },
  {
    id: "act-11",
    event_type: "contact_added",
    description: "Added contact: Bob Johnson (Project Manager)",
    actor_name: "Sarah Chen",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { contact_email: "bob@acme.com" },
    created_at: "2026-02-13T10:30:00Z",
  },
  {
    id: "act-12",
    event_type: "task_reassigned",
    description: "Reassigned \"Schedule follow-up with VP\" to Mike Torres",
    actor_name: "Sarah Chen",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { task_id: "t2", from: "tm1", to: "tm2" },
    created_at: "2026-02-12T14:15:00Z",
  },
  {
    id: "act-13",
    event_type: "brief_updated",
    description: "Account brief updated with new budget information",
    actor_name: "System",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { section: "budgets" },
    created_at: "2026-02-12T10:00:00Z",
  },
  {
    id: "act-14",
    event_type: "deal_won",
    description: "Deal \"Globex Q1 Sprint\" marked as Closed Won ($30,000)",
    actor_name: "Mike Torres",
    account_name: "Globex Inc",
    account_id: "2",
    metadata: { deal_id: "d6", amount: 30000 },
    created_at: "2026-02-11T16:00:00Z",
  },
  {
    id: "act-15",
    event_type: "account_created",
    description: "New account created: Umbrella Co",
    actor_name: "Mike Torres",
    account_name: "Umbrella Co",
    account_id: "4",
    metadata: {},
    created_at: "2026-02-11T09:00:00Z",
  },
  {
    id: "act-16",
    event_type: "deal_lost",
    description: "Deal \"Waystar — Brand Audit\" marked as Closed Lost ($50,000)",
    actor_name: "Sarah Chen",
    account_name: "Waystar Royco",
    account_id: "5",
    metadata: { deal_id: "d7", amount: 50000 },
    created_at: "2026-02-10T15:00:00Z",
  },
  {
    id: "act-17",
    event_type: "task_created",
    description: "Created task \"Prepare quarterly budget review deck\"",
    actor_name: "Sarah Chen",
    account_name: "Globex Inc",
    account_id: "2",
    metadata: { task_id: "t3", source: "manual" },
    created_at: "2026-02-10T11:00:00Z",
  },
  {
    id: "act-18",
    event_type: "intelligence_received",
    description: "New transcript intelligence: weekly sync milestones and capacity",
    actor_name: "System",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { intelligence_id: "2", source: "transcript" },
    created_at: "2026-02-09T16:30:00Z",
  },
  {
    id: "act-19",
    event_type: "account_archived",
    description: "Archived account Waystar Royco",
    actor_name: "Sarah Chen",
    account_name: "Waystar Royco",
    account_id: "5",
    metadata: {},
    created_at: "2026-02-09T10:00:00Z",
  },
  {
    id: "act-20",
    event_type: "deal_stage_changed",
    description: "Moved \"Globex Q3 Strategy Package\" from Lead to Proposal",
    actor_name: "Mike Torres",
    account_name: "Globex Inc",
    account_id: "2",
    metadata: { deal_id: "d2", from_stage: "lead", to_stage: "proposal" },
    created_at: "2026-02-08T14:00:00Z",
  },
  {
    id: "act-21",
    event_type: "email_synced",
    description: "5 new emails synced from Gmail",
    actor_name: "System",
    account_name: null,
    account_id: null,
    metadata: { count: 5 },
    created_at: "2026-02-08T10:30:00Z",
  },
  {
    id: "act-22",
    event_type: "workflow_applied",
    description: "Applied \"Thrive Local Onboarding\" workflow",
    actor_name: "Sarah Chen",
    account_name: "Initech",
    account_id: "3",
    metadata: { workflow_id: "wf-thrive-onboarding" },
    created_at: "2026-02-07T15:00:00Z",
  },
  {
    id: "act-23",
    event_type: "note_added",
    description: "Added note: \"Need to schedule onboarding call with new POC\"",
    actor_name: "Mike Torres",
    account_name: "Initech",
    account_id: "3",
    metadata: {},
    created_at: "2026-02-07T11:00:00Z",
  },
  {
    id: "act-24",
    event_type: "contact_added",
    description: "Added contact: Jane Smith (VP of Operations)",
    actor_name: "Sarah Chen",
    account_name: "Acme Corp",
    account_id: "1",
    metadata: { contact_email: "jane@acme.com" },
    created_at: "2026-02-06T09:30:00Z",
  },
  {
    id: "act-25",
    event_type: "account_created",
    description: "New account created: Initech",
    actor_name: "Mike Torres",
    account_name: "Initech",
    account_id: "3",
    metadata: {},
    created_at: "2026-02-05T10:00:00Z",
  },
];
